networks:
  backend:

services:
  librarydb:
    container_name: librarydb-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - backend
    ports:
      - "8001:1433" 

  library.webapi:
    container_name: Library-api
    image: ${DOCKER_REGISTRY-}librarywebapi
    build:
      context: .
      dockerfile: Presentation/Library.WebAPI/Dockerfile
    volumes:
      - ./Infrustructure/Library.Data/FileStorage/BookImages:/app/Infrustructure/Library.Data/FileStorage/BookImages
    networks:
      - backend
    environment:
      - Jwt__Secret=superSecretKey@345432242344324245
      - Jwt__Issuer=https://localhost:5001
      - Jwt__Audience=https://localhost:5001
      - Jwt__TokenValidityInMinutes=30
      - ConnectionStrings__DefaultConnection=Server=librarydb;Database=LibraryDb;User Id=sa;Password=password@12345#;TrustServerCertificate=True;
    depends_on:
      - librarydb
      - library-redis
      - rabbitmq
    ports:
      - "8002:80"
      - "8082:443"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend
  
  library-redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend