name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore WebAPI dependencies
        run: dotnet restore Presentation/Library.WebAPI/Library.WebAPI.csproj

      - name: Restore Test dependencies
        run: dotnet restore Tests/Library.Tests/Library.Tests.csproj

      - name: Build WebAPI
        run: dotnet build Presentation/Library.WebAPI/Library.WebAPI.csproj --configuration Release

      - name: Build Tests
        run: dotnet build Tests/Library.Tests/Library.Tests.csproj --configuration Release

      - name: Run Tests
        run: dotnet test Tests/Library.Tests/Library.Tests.csproj --configuration Release --verbosity normal

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push
